from pathlib import Path
import json
O=Path(__file__).resolve().parent
d=json.loads((O/'posterboard_hybrid.json').read_text())
html='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Posterboard gate tradeoffs</title>
<style>*{box-sizing:border-box}body{margin:0;background:#f4f6f8;color:#173247;font:16px/1.55 system-ui,sans-serif}main{max-width:1260px;margin:auto;padding:28px}h1{font-size:38px;line-height:1.1}h2{font-size:23px;margin-top:30px}.intro{max-width:950px}.controls{display:flex;flex-wrap:wrap;gap:22px;padding:20px;background:white;border-radius:10px}.controls label{display:block;min-width:230px}input{width:215px}.note{background:#e5edf4;border-left:4px solid #3476bd;padding:14px 18px}.scroll{overflow-x:auto}table{border-collapse:collapse;width:100%;background:white;font-size:15px}td,th{padding:10px;text-align:left;border-bottom:1px solid #d7dfe6;white-space:nowrap}tr.selected{background:#dcebdc}button{font:inherit;border:0;background:none;text-align:left;color:#17518a;cursor:pointer;text-decoration:underline}.views{display:grid;grid-template-columns:1fr 1fr;gap:24px}.view{background:white;border-radius:8px;padding:16px}svg{width:100%;height:340px}small{color:#526676}a{color:#185999}@media(max-width:700px){.views{grid-template-columns:1fr}main{padding:16px}h1{font-size:30px}}</style>
<main><h1>Posterboard + printed framing</h1><p class="intro">Same 2700 × 2700 mm gate, 1500 mm opening and existing PVC backing. The two strongest candidates to test are <b>600 × 450 mm sheets with a middle support rib</b> for low cost, and <b>300 × 250 mm inserts</b> for smaller replaceable panels. Nominal panel sizes; a few end fillers preserve the exact gate dimensions.</p>
<p class="note">Study, not a finished frame design. Shared rails avoid two separate frames along every seam. PETG figures include a 20% rail allowance for joints/nodes, 250 g for PVC mounts, and 10% printing waste. Existing PVC, brace connectors, bases and anchors are excluded.</p>
<div class="controls"><label>Rail plastic cross-section: <b id="areaVal"></b> mm²<br><input id="area" type="range" min="20" max="40" value="28" step="1"></label><label>Filament price: $<b id="priceVal"></b>/kg<br><input id="price" type="range" min="10" max="35" value="20" step="1"></label><label>Posterboard price: $<b id="boardVal"></b>/sheet<br><input id="board" type="range" min="0.37" max="4" value="0.99" step="0.01"></label></div>
<h2>Material and effort comparison</h2><p>Click a size to see its face layout and a verified sheet-cut pattern. Costs are for the new face system only.</p><div class="scroll"><table><thead><tr><th>Nominal panels</th><th>Pieces</th><th>Sheets</th><th>Rail length</th><th>PETG</th><th>1 kg spools</th><th>Consumed material</th><th>Whole-spool purchase</th></tr></thead><tbody id="rows"></tbody></table></div>
<div class="views"><section class="view"><h2 id="choice"></h2><svg id="gate" viewBox="-100 -100 2900 2900" aria-label="Gate panel layout"></svg><p id="effort"></p></section><section class="view"><h2>One 22 × 28 inch stock sheet</h2><svg id="stock" viewBox="-30 -30 620 780" aria-label="Posterboard cutting pattern"></svg><p id="yield"></p></section></div>
<h2>What changes the result?</h2><p><b>Paper size:</b> a 300 mm square is just too wide to get two across the 558.8 mm stock width. A 300 × 250 rectangle yields four per sheet; mixed orientation yields five 300 × 200 rectangles. The true area-only minimum is 13 sheets, but these repeatable layouts need 17–28.</p>
<p><b>Panel support:</b> smaller bays should flex less, but more rail joints do not automatically make the whole gate stronger. The middle-rib option retains 20 paper pieces while supporting each large panel as two roughly 300 × 450 mm bays. Ribs need light retainers to work under wind from both directions.</p>
<p><b>Printer size:</b> use rail bodies up to 150 mm long plus compact connectors, within an approximately 170 mm envelope. Several rails can print together; rail piece counts are not print-job counts. One-piece 150 mm panel frames are possible, but duplicate the shared edges and use more material.</p>
<p><b>Outdoor use:</b> the $0.99 listing describes cardstock and gives no wet-weather rating. Treat it as a replaceable dry-weather insert; framing does not waterproof it. Wind area remains approximately 5.04 m², so existing guying/ballast remains relevant.</p>
<p><a href="posterboard_hybrid.md">Detailed study</a> · <a href="posterboard_hybrid.csv">Calculation table</a> · <a href="posterboard_hybrid.json">Exact layouts and assumptions</a></p>
<small>Sources: <a href="https://www.hobbylobby.com/Art-Supplies/Project-Supplies/Poster-Projects/Poster-Board---22-x-28/p/81118411">Hobby Lobby $0.99 cardstock</a>; PETG density 1.28 g/cm³. Prices exclude tax/shipping and are scenario assumptions except the listed posterboard price. No stiffness or wind rating is claimed.</small></main>
<script>const DATA=__DATA__;let selected=6;const $=id=>document.getElementById(id);const label=r=>r.option==='600x450_with_mid_rib'?'600 × 450 + middle rib':r.option.replace('x',' × ');function mass(r){let rail=r.shared_rails_m*Number($('area').value)*.00128;if(r.extra_support_ribs_m)rail+=r.extra_support_ribs_m*r.extra_support_rib_area_mm2*.00128;return(rail*1.2+.25)*1.1}function draw(){let r=DATA.options[selected],k=r.option==='600x450_with_mid_rib'?'600x450':r.option,l=DATA.layouts[k];$('choice').textContent=label(r)+' mm';let s=l.panels.map(([x,y,w,h],i)=>`<rect x="${x}" y="${y}" width="${w}" height="${h}" fill="${i%2?'#d2e3f6':'#e9f0f8'}" stroke="#3270b4" stroke-width="8"/>`).join('');if(r.extra_support_ribs_m)s+='<rect x="300" y="300" width="2100" height="2100" fill="none" stroke="#e78d36" stroke-width="15" stroke-dasharray="45 20"/>';$('gate').innerHTML=s;$('effort').textContent=`${r.panels} paper pieces; approximately ${r.rail_pieces_max_150mm} straight printed rail/rib pieces before nodes, mounts and retaining clips. Existing PVC is not drawn.`;$('stock').innerHTML=`<rect width="558.8" height="711.2" fill="#edf0df" stroke="#607766" stroke-width="2"/>`+l.stock_pattern.map(([x,y,w,h],i)=>`<rect x="${x}" y="${y}" width="${w}" height="${h}" fill="${i%2?'#bcd6ed':'#d4e5f3'}" stroke="#3270b4" stroke-width="2"/><text x="${x+w/2}" y="${y+h/2}" text-anchor="middle" font-family="Arial" font-size="22">${w} × ${h}</text>`).join('');$('yield').textContent=`${l.stock_pattern.length} standard pieces from this pattern; ${l.full_panels_required} standard pieces needed.`+(l.trim_sheet.length?` Plus one sheet for ${l.trim_sheet.length} end fillers.`:'')+` ${r.sheets} sheets per gate; ${r.paper_yield_percent}% nominal area yield.`;}function update(){let price=+$('price').value,board=+$('board').value;for(let id of ['area','price','board'])$(id+'Val').textContent=(+$ (id).value).toFixed(id==='board'?2:0);$('rows').innerHTML=DATA.options.map((r,i)=>{let kg=mass(r);return`<tr class="${i===selected?'selected':''}"><td><button onclick="select(${i})">${label(r)}</button></td><td>${r.panels}</td><td>${r.sheets}</td><td>${r.shared_rails_m.toFixed(1)} m${r.extra_support_ribs_m?' + 8.4 m rib':''}</td><td>${kg.toFixed(2)} kg</td><td>${Math.ceil(kg)}</td><td>$${(kg*price+r.sheets*board).toFixed(2)}</td><td>$${(Math.ceil(kg)*price+r.sheets*board).toFixed(2)}</td></tr>`}).join('');draw()}function select(i){selected=i;update()}for(let id of ['area','price','board'])$(id).addEventListener('input',update);update();</script></html>'''
html=html.replace('__DATA__',json.dumps(d)).replace('$ (id)','$'+'(id)')
(O/'posterboard_hybrid.html').write_text(html)
print('Wrote interactive local comparison')
