"""Package the native Blender comparison, renders and explicitly provisional coupons."""
from pathlib import Path
import csv,html,json,zipfile
from PIL import Image
ROOT=Path(__file__).resolve().parents[1]
O=ROOT/'output/posterboard_concepts'
options=json.loads((O/'options.json').read_text())
images=sorted((O/'renders').glob('*.png'))
assert len(images)==12, len(images)
fields=['id','name','card','inserts','sheets','cuts','outer','opening','pack','PETG_kg','spools','consumed_USD','cash_USD']
with (O/'comparison.csv').open('w') as f:
 w=csv.DictWriter(f,fieldnames=fields,extrasaction='ignore');w.writeheader();w.writerows(options)
rows=''.join('<tr>'+''.join(f'<td>{html.escape(str(v))}</td>' for v in [o['id']+' / '+o['name'],f"{o['card'][0]:g} × {o['card'][1]:g}",o['cuts'],f"{o['pack'][0]:.0f} × {o['pack'][1]:.0f}",f"{o['PETG_kg']:.2f} kg",f"${o['consumed_USD']:.0f}"])+'</tr>' for o in options)
cards=''.join(f'<figure id="scene-{i+1}"><a href="renders/{p.name}"><img loading="lazy" src="renders/{p.name}" alt="{p.stem.replace("_"," ")}"></a><figcaption>Scene {i+1:02}: {html.escape(p.stem[3:].replace("_"," ").title())}</figcaption></figure>' for i,p in enumerate(images))
coupons=''.join(f'<li><a href="prototype_coupons/{p.name}">{p.name}</a></li>' for p in sorted((O/'prototype_coupons').glob('*.stl')))
(O/'index.html').write_text('''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>FPV gate — uniform posterboard options</title><style>body{font:17px/1.55 system-ui,sans-serif;background:#edf1f3;color:#16283a;max-width:1200px;margin:40px auto;padding:0 24px}h1{font-size:36px;line-height:1.15}a{color:#075e98}table{border-collapse:collapse;width:100%;background:white;font-size:15px}td,th{padding:12px;text-align:left;border-bottom:1px solid #ccd5dc}figure{margin:28px 0;background:white;padding:12px;border-radius:10px}img{width:100%;height:auto}figcaption{padding:8px}nav{display:flex;gap:22px;flex-wrap:wrap}.note{background:#fff3d5;padding:16px;border-radius:8px}pre{white-space:pre-wrap;font-family:inherit}</style><h1>Four folding FPV gate options</h1><p>Uniform slide-in posterboard. One PVC backing frame. Four loaded face bundles under 1.2 m long.</p><nav><a href="Posterboard_Gate_Options.blend">Open native Blender model</a><a href="Posterboard_Options.pdf">12-page visual guide</a><a href="CONCEPT_GUIDE.md">Detailed design notes</a><a href="comparison.csv">Cost / size table</a></nav><p><strong>Recommended: B / half sheets.</strong> One cut per 22 × 28 in sheet; 24 identical 14 × 22 in inserts. Four book-fold bundles about 1079 × 563 × 40 mm. Opening 1595 mm; outside 2720 mm.</p><table><tr><th>Option</th><th>Insert, mm</th><th>Cuts / gate</th><th>Folded L × W, mm</th><th>PETG</th><th>Face materials</th></tr>'''+rows+'''</table><p>Planning quantities at $20/kg PETG and $0.99 per sheet; includes joint/waste allowances. Excludes PVC, bases, brace clamps, anchors, labor and tax. These are not slicer-derived bills of materials.</p><p class="note"><strong>Concept and fit-test package.</strong> Seven manifold coupon meshes fit the A1 Mini and target support-free printing. Full rail nodes, twin bridge keys, hinge adapters, PVC keeper and mounting interfaces still require detail and physical fit testing. No wind, fatigue or impact rating is claimed. Posterboard is a dry-weather, replaceable face.</p>'''+cards+'''<h2>Printable fit coupons</h2><p>Print and test one joint/channel first. These files do not constitute a complete gate kit.</p><ul>'''+coupons+'''</ul><h2>Review / assembly</h2><p>Select scenes 01–12 in Blender's scene selector. Objects and collections remain editable; the guide is also embedded in Blender's text blocks. The face docks detach from PVC before folding. The frame splits at its four midpoints, and travels separately.</p><p>Model checks: exact ring coverage, non-overlapping stock cuts, uniform inserts, transport leaf lengths, coupon manifoldness and print-bed envelopes. See <a href="layout_validation.json">layout validation</a> and <a href="prototype_validation.json">coupon geometry</a>.</p></html>''')
pages=[Image.open(p).convert('RGB') for p in images]
pages[0].save(O/'Posterboard_Options.pdf',save_all=True,append_images=pages[1:],resolution=150)
for p in pages:p.close()
with zipfile.ZipFile(O/'Posterboard_Concepts.zip','w',zipfile.ZIP_DEFLATED,compresslevel=6) as z:
 for p in sorted(O.rglob('*')):
  if p.is_file() and p.suffix not in ['.zip','.blend1','.log'] and p.name!='.DS_Store':z.write(p,Path('output/posterboard_concepts')/p.relative_to(O))
 for name in ['build_posterboard_concepts.py','posterboard_options.py','validate_posterboard_options.py','package_posterboard_concepts.py','build_gate.py','face_geometry.py']:
  z.write(ROOT/'scripts'/name,Path('scripts')/name)
 z.writestr('README.txt','Open output/posterboard_concepts/index.html or Posterboard_Gate_Options.blend.\nSource rebuild: blender -b --python scripts/build_posterboard_concepts.py\nValidation: python3 scripts/validate_posterboard_options.py\nPackaging: python3 scripts/package_posterboard_concepts.py (requires Pillow)\nGeneration currently uses macOS Arial font paths; adjust build_gate.py for another OS.\nDo not run build_gate.py directly: it regenerates the earlier Coroplast gate.\n')
print(f'Packaged {len(images)} scenes, {len(options)} options, seven fit coupons.')
