from pathlib import Path
from PIL import Image
import html,json,zipfile
R=Path(__file__).resolve().parents[1];O=R/'output/rigid_whole_sheet'
imgs=sorted((O/'renders').glob('*.png'));assert len(imgs)==6
pages=[Image.open(p).convert('RGB') for p in imgs];pages[0].save(O/'Rigid_Gate_Visual_Guide.pdf',save_all=True,append_images=pages[1:],resolution=150)
for p in pages:p.close()
figs=''.join(f'<figure><a href="renders/{p.name}"><img loading="lazy" src="renders/{p.name}" alt="{p.stem}"></a></figure>' for p in imgs)
(O/'index.html').write_text('''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Rigid whole-sheet gate and printable 1:15 model</title><style>body{font:17px/1.6 system-ui;max-width:1100px;margin:40px auto;padding:0 24px;color:#183044;background:#edf1f3}h1{line-height:1.15}a{color:#075b92}nav{display:flex;gap:24px;flex-wrap:wrap}figure{margin:24px 0}img{width:100%;border-radius:8px}.card{background:white;border-radius:8px;padding:20px;margin:20px 0}</style><h1>Whole sheets. Four rigid borders.</h1><p><strong>Full-size audit:</strong> <a href="FULL_SIZE_PARTS_AUDIT.md">Part quantities and printer-volume findings</a>. Rear ribs are oversized; final production connectors remain unfinished. The miniature is a separate printable assembly model.</p><p>No hinges or fold locks. Twelve uncut posterboard sheets in four 2146 × 563 mm borders. Outside 2708 mm; opening 1583 mm. Eight corner keys and sixteen PVC docks remain removable.</p><nav><a href="Rigid_Whole_Sheet_Gate.blend">Blender model</a><a href="Rigid_Gate_Visual_Guide.pdf">Visual guide PDF</a><a href="DESIGN_AND_PRINT_GUIDE.md">Design and print instructions</a></nav><div class="card"><h2>Print the 1:15 model</h2><p>The four border pieces measure 143 × 38 mm each. The assembled model is 181 mm square. Faces are printed plastic; miniature thicknesses and press-fit keys are enlarged for practical printing.</p><ol><li><a href="sliced/Mini_Fit_Test_A1Mini_PLA/Mini_Fit_Test_A1Mini_PLA.3mf">Print the fit test and feet first</a> — about 7 g PLA / 23 minutes.</li><li><a href="sliced/Mini_1to15_A1Mini_PLA/Mini_1to15_A1Mini_PLA.3mf">Complete miniature: four borders and eight keys</a> — about 35 g PLA / 73 minutes.</li></ol><p>A1 Mini, 0.4 mm nozzle, 0.20 mm layers, Generic PLA, supports off. Import at <strong>100% file size</strong>. Check your printer, filament and build plate in Bambu Studio before printing. No physical print has yet been tested.</p><p><a href="printable/Mini_1to15_Four_Borders_LAYOUT.3mf">Geometry-only model layout</a> · <a href="printable/Mini_Fit_Test_and_Feet_LAYOUT.3mf">Geometry-only fit layout</a> · <a href="print_checks.json">Slice and geometry checks</a></p></div><p>Full-size planning estimate: 1.84 kg PETG, targeting two 1 kg spools, and about $49 consumed face materials at $20/kg filament and $0.99/sheet. Excludes PVC, anchors, brace clamps and labor. Full-size production connector details and physical wind/fit validation remain outstanding.</p>'''+figs+'''<p>Previous folding comparison is committed as <code>d6d0196</code>. This iteration accepts 2.15 m long transport sections. The miniature evaluates layout and assembly, while actual paper/PVC interfaces require the separate 1:1 fit samples.</p></html>''')
with zipfile.ZipFile(O/'Rigid_Gate_and_Miniature.zip','w',zipfile.ZIP_DEFLATED,compresslevel=6) as z:
 for p in sorted(O.rglob('*')):
  if p.is_file() and p.suffix not in ['.zip','.blend1','.log','.gcode'] and p.name!='.DS_Store':z.write(p,Path('output/rigid_whole_sheet')/p.relative_to(O))
 for name in ['build_rigid_whole_sheet.py','slice_rigid_mini.py','validate_rigid_mini.py','audit_rigid_gate_parts.py','package_rigid_whole_sheet.py','build_posterboard_concepts.py','posterboard_options.py','build_gate.py','face_geometry.py']:z.write(R/'scripts'/name,Path('scripts')/name)
 z.writestr('README.txt','Start at output/rigid_whole_sheet/index.html.\nUse the sliced 3MF projects with Bambu Studio; verify printer/filament/plate before printing.\nRebuild: blender -b --python scripts/build_rigid_whole_sheet.py\nSlice verification on macOS: python3 scripts/slice_rigid_mini.py\nValidate: python3 scripts/validate_rigid_mini.py\nPackaging requires Pillow: python3 scripts/package_rigid_whole_sheet.py\n')
print('Packaged Blender, six visual scenes, five miniature STL masters, two 3MF layouts, two sliced projects and five full-size fit samples.')
